# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Global settings
timezone: America/New_York

# Site settings
title: GeoSys Int.
email: mrossi@geosysint.com
description: >
  GeoSystems International, Inc. (GSI) is dedicated to the use of sound
  scientific methods for the investigation of spatially distributed phenomena.
baseurl: "" # the subpath of your site, e.g. /blog (No slash at the end)
url: "http://www.geosysint.com" # the base hostname & protocol for your site (No slash at the end)
domain: "www.geosysint.com"
author: "Thomas Pakh, Mario Rossi, Sebastian Rossi"

# Build settings
markdown: kramdown

collections:
  projects:
    output: true
    permalink: /projects/:title/
  papers:
    output: true
    permalink: /papers/:path
  members:
    output: true
    permalink: /personnel/:path